--- 
    name: Pipeline Workflow
  
  
    on:
      push:
        branches:
          - master
  
  
    
    permissions:
      contents: write
    
    jobs:
      pipeline:
        runs-on: ubuntu-latest
  
      
        steps:
  
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Tags and Release
            uses: pantheon-systems/action-autotag@v0
            with:
              gh-token: ${{ secrets.GITHUB_TOKEN }}
